// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzUIQXQCYupa8H19spgikuDj5wbWwsw9I',
    appId: '1:345242197922:web:a596a0af3ef50b3ac89cfb',
    messagingSenderId: '345242197922',
    projectId: 'katalog-378ff',
    authDomain: 'katalog-378ff.firebaseapp.com',
    storageBucket: 'katalog-378ff.firebasestorage.app',
    measurementId: 'G-071CPZWMBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeYeaoJT0WlHHlfGb6oGIJpQw-ipIMwRQ',
    appId: '1:345242197922:android:b126f3d124e40ee1c89cfb',
    messagingSenderId: '345242197922',
    projectId: 'katalog-378ff',
    storageBucket: 'katalog-378ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRJdRL4BBHwSgn48obVUiZ2NPhQn27Vo4',
    appId: '1:345242197922:ios:112056e9c02c01a7c89cfb',
    messagingSenderId: '345242197922',
    projectId: 'katalog-378ff',
    storageBucket: 'katalog-378ff.firebasestorage.app',
    iosBundleId: 'com.example.katalog',
  );
}
